name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main  # or change to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 565748443817.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t strapi-app .

      - name: Tag Docker image
        run: |
          docker tag strapi-app:latest 565748443817.dkr.ecr.us-east-2.amazonaws.com/rupesh-strapi-app:latest

      - name: Push image to ECR
        run: |
          docker push 565748443817.dkr.ecr.us-east-2.amazonaws.com/rupesh-strapi-app:latest
