name: CI/CD for Strapi to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t rupesh-strapi-app .

      - name: Tag Docker image
        run: docker tag rupesh-strapi-app:latest 565748443817.dkr.ecr.us-east-2.amazonaws.com/rupesh-strapi-app:latest

      - name: Push Docker image
        run: docker push 565748443817.dkr.ecr.us-east-2.amazonaws.com/rupesh-strapi-app:latest
